name: studdybuddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.0

  http: ^1.1.0
  dio: ^5.4.0

  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  file_picker: ^8.1.4
  path_provider: ^2.1.1

  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  intl: ^0.18.1
  go_router: ^16.2.4
  animations: ^2.0.11
  flutter_screenutil: ^5.9.3
  animated_text_kit: ^4.2.3
  flutter_gen: ^5.12.0
  chopper: ^8.4.0
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  chopper_generator: ^8.4.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 900
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600